version: '3'
services:
  vue:
    build: ./vueproject
    ports:
      - 8888:8080
    volumes:
      - ./vueproject:/app
      - ./vueproject/n_modules:/app/node_modules
    stdin_open: true
    tty: true
    #command: npm run serve

  flask:
    build: ./flaskproject
    ports:
      - 5000:5000
    volumes:
      - ./flaskproject:/app
    depends_on:
      - db
    tty: true
    #command: flask run --host 0.0.0.0 --port 5000
    command: sh -c "while ! mysqladmin ping -h db -u root -proot --silent; do sleep 3; done && echo 'mysql running!!!' && flask run --host 0.0.0.0 --port 5000"

  db:
    build: ./db
    ports:
      - 3333:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'

    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-sql
      - ./db/log:/var/log/mysql

    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin



