
version: 2.1
jobs:
  build:
    working_directory: ~/circleci-autumnhack
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - run: pip install -r ./flaskproject/requirements.txt
      - run: echo "hello world"

  test:
    working_directory: ~/circleci-autumnhack
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      #- run: pip install -r /flaskproject/requirements.txt
      - run: echo "Test Finished"

  deploy:
    working_directory: ~/circleci-autumnhack
    docker:
      - image: circleci/python:3.7.6
    steps: # ssh接続して、接続先のdeploy.shを実行する
      - checkout
      #- run: pip install -r requirements.txt
      - add_ssh_keys:
          fingerprints:
            - "eb:fd:b4:77:23:26:9d:71:fa:27:80:16:c3:5f:a8:9a"
      - run: ssh -o "StrictHostKeyChecking=no" $SSH_USER@$SSH_HOST $COMMAND
      - run: echo "Deploy Finished"


workflows:
  version: 2.1
  build_and_test: # workflow名
    jobs:
      - build
      - test:
          requires: # buildが成功したら実行する
            - build
      - deploy:
          requires: # testが成功したら実行する
            - test
          filters: # masterブランチのみjobを実行
            branches:
              only: master