
version: 2.1
jobs:
  build:
    working_directory: ~/circleci-autumnhack
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: pip install -r ./flaskproject/requirements.txt
      - run: echo "hello world"

  test:
    working_directory: ~/circleci-autumnhack
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: echo "Test Finished"

  deploy:
    working_directory: ~/circleci-autumnhack
    docker:
      - image: circleci/python:3.7.6
    steps: # ssh接続して、接続先のdeploy.shを実行する
      - checkout
      - run: pip install -r requirements.txt
      - add_ssh_keys:
          fingerprints:
            - "b8:c4:b1:11:bd:a2:3b:05:3b:84:6b:12:07:10:a2:28"
      - run: ssh -o "StrictHostKeyChecking=no" -p 222 toru@118.27.21.217 "~/deploy.sh"


workflows:
  version: 2.1
  build_and_test: # workflow名
    jobs:
      - build
      #- test:
      #    requires: # buildが成功したら実行する
      #      - build
      #- deploy:
      #    requires: # testが成功したら実行する
      #      - test
      #    filters: # masterブランチのみjobを実行
      #      branches:
      #        only: master